<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'parentid' => '8',
    'catname' => '挽回爱情',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=9&siteid=1',
    'status' => '1',
  ),
  48 => 
  array (
    'catid' => '48',
    'parentid' => '47',
    'catname' => '挽回爱情',
    'siteid' => '1',
    'listorder' => '1',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=48&siteid=1',
    'status' => '1',
  ),
  10 => 
  array (
    'catid' => '10',
    'parentid' => '8',
    'catname' => '挽回婚姻',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=10&siteid=1',
    'status' => '1',
  ),
  49 => 
  array (
    'catid' => '49',
    'parentid' => '47',
    'catname' => '挽回婚姻',
    'siteid' => '1',
    'listorder' => '2',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=49&siteid=1',
    'status' => '1',
  ),
  50 => 
  array (
    'catid' => '50',
    'parentid' => '47',
    'catname' => '分离小三',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=50&siteid=1',
    'status' => '1',
  ),
  32 => 
  array (
    'catid' => '32',
    'parentid' => '27',
    'catname' => '办公环境',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=32&siteid=1',
    'status' => '1',
  ),
  11 => 
  array (
    'catid' => '11',
    'parentid' => '8',
    'catname' => '恋爱课堂',
    'siteid' => '1',
    'listorder' => '3',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=11&siteid=1',
    'status' => '1',
  ),
  14 => 
  array (
    'catid' => '14',
    'parentid' => '47',
    'catname' => '关系维护',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=14&siteid=1',
    'status' => '1',
  ),
  12 => 
  array (
    'catid' => '12',
    'parentid' => '8',
    'catname' => '幸福婚姻5s店',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=12&siteid=1',
    'status' => '1',
  ),
  33 => 
  array (
    'catid' => '33',
    'parentid' => '27',
    'catname' => '荣誉资质',
    'siteid' => '1',
    'listorder' => '4',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=33&siteid=1',
    'status' => '1',
  ),
  51 => 
  array (
    'catid' => '51',
    'parentid' => '27',
    'catname' => '公司资质',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=51&siteid=1',
    'status' => '1',
  ),
  15 => 
  array (
    'catid' => '15',
    'parentid' => '47',
    'catname' => '情商培训',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=15&siteid=1',
    'status' => '1',
  ),
  13 => 
  array (
    'catid' => '13',
    'parentid' => '8',
    'catname' => '分离小三',
    'siteid' => '1',
    'listorder' => '5',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=13&siteid=1',
    'status' => '1',
  ),
  16 => 
  array (
    'catid' => '16',
    'parentid' => '47',
    'catname' => '两性关系技巧',
    'siteid' => '1',
    'listorder' => '6',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=16&siteid=1',
    'status' => '1',
  ),
  18 => 
  array (
    'catid' => '18',
    'parentid' => '17',
    'catname' => '首席专家',
    'siteid' => '1',
    'listorder' => '18',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=18&siteid=1',
    'status' => '1',
  ),
  19 => 
  array (
    'catid' => '19',
    'parentid' => '17',
    'catname' => '资深专家',
    'siteid' => '1',
    'listorder' => '19',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=19&siteid=1',
    'status' => '1',
  ),
  20 => 
  array (
    'catid' => '20',
    'parentid' => '17',
    'catname' => '顾问专家',
    'siteid' => '1',
    'listorder' => '20',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=20&siteid=1',
    'status' => '1',
  ),
  22 => 
  array (
    'catid' => '22',
    'parentid' => '21',
    'catname' => '恋爱',
    'siteid' => '1',
    'listorder' => '22',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=22&siteid=1',
    'status' => '1',
  ),
  23 => 
  array (
    'catid' => '23',
    'parentid' => '21',
    'catname' => '婚姻',
    'siteid' => '1',
    'listorder' => '23',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=23&siteid=1',
    'status' => '1',
  ),
  24 => 
  array (
    'catid' => '24',
    'parentid' => '21',
    'catname' => '小三',
    'siteid' => '1',
    'listorder' => '24',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=24&siteid=1',
    'status' => '1',
  ),
  25 => 
  array (
    'catid' => '25',
    'parentid' => '21',
    'catname' => '出轨',
    'siteid' => '1',
    'listorder' => '25',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=25&siteid=1',
    'status' => '1',
  ),
  26 => 
  array (
    'catid' => '26',
    'parentid' => '21',
    'catname' => '经典策略',
    'siteid' => '1',
    'listorder' => '26',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=26&siteid=1',
    'status' => '1',
  ),
  41 => 
  array (
    'catid' => '41',
    'parentid' => '35',
    'catname' => '爱恋图库',
    'siteid' => '1',
    'listorder' => '41',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=41&siteid=1',
    'status' => '1',
  ),
  52 => 
  array (
    'catid' => '52',
    'parentid' => '17',
    'catname' => '律师',
    'siteid' => '1',
    'listorder' => '52',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=52&siteid=1',
    'status' => '1',
  ),
  8 => 
  array (
    'catid' => '8',
    'parentid' => '0',
    'catname' => '保卫爱情',
    'siteid' => '1',
    'listorder' => '200',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=8&siteid=1',
    'status' => '1',
  ),
  47 => 
  array (
    'catid' => '47',
    'parentid' => '0',
    'catname' => '解决方案',
    'siteid' => '1',
    'listorder' => '300',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=47&siteid=1',
    'status' => '1',
  ),
  17 => 
  array (
    'catid' => '17',
    'parentid' => '0',
    'catname' => '专家团队',
    'siteid' => '1',
    'listorder' => '400',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=17&siteid=1',
    'status' => '1',
  ),
  21 => 
  array (
    'catid' => '21',
    'parentid' => '0',
    'catname' => '客户见证',
    'siteid' => '1',
    'listorder' => '500',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=21&siteid=1',
    'status' => '1',
  ),
  46 => 
  array (
    'catid' => '46',
    'parentid' => '0',
    'catname' => '爱恋视频',
    'siteid' => '1',
    'listorder' => '999',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=46&siteid=1',
    'status' => '1',
  ),
  40 => 
  array (
    'catid' => '40',
    'parentid' => '0',
    'catname' => '情感测试',
    'siteid' => '1',
    'listorder' => '1000',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=40&siteid=1',
    'status' => '1',
  ),
  43 => 
  array (
    'catid' => '43',
    'parentid' => '0',
    'catname' => '资料分享',
    'siteid' => '1',
    'listorder' => '1001',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=43&siteid=1',
    'status' => '1',
  ),
  44 => 
  array (
    'catid' => '44',
    'parentid' => '0',
    'catname' => '题库下载',
    'siteid' => '1',
    'listorder' => '1002',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=44&siteid=1',
    'status' => '1',
  ),
  45 => 
  array (
    'catid' => '45',
    'parentid' => '0',
    'catname' => '电子书籍',
    'siteid' => '1',
    'listorder' => '1003',
    'type' => '0',
    'url' => 'http://www.ailianlove.com/index.php?m=mobile&a=lists&catid=45&siteid=1',
    'status' => '1',
  ),
);
?>